# -*- coding: utf-8 -*-
"""04_22301205_UtshaBasak

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O13YQpGdiYziReH8L4nfIsPUOgaZ3o2s

# ***Loan Approval Prediction Model***
"""

#@title Checking null values

import pandas as pd
from pathlib import Path

# Dataset lives at <repo>/data/, resolved relative to this file so the script
# can be run from any working directory.
DATA_PATH = Path(__file__).resolve().parents[1] / 'data' / 'Loan Approval Dataset.csv'

csv_file = pd.read_csv(DATA_PATH)
csv_file = csv_file.dropna() # no null values in any column
csv_file.info()

#@title Types of objects in a column

print(csv_file['person_gender'].value_counts())
print(csv_file['person_education'].value_counts())
print(csv_file['person_home_ownership'].value_counts())
print(csv_file['loan_intent'].value_counts())
print(csv_file['previous_loan_defaults_on_file'].value_counts())

#@title Assigning object values to categorical values

from sklearn.preprocessing import LabelEncoder
encode = LabelEncoder()

csv_file['person_gender'] = csv_file['person_gender'].map({'male': 0, 'female': 1})
csv_file['person_education'] = csv_file['person_education'].map({'Bachelor': 0, 'Associate': 1, 'High School': 2, 'Master': 3, 'Doctorate': 4})
csv_file['person_home_ownership'] = csv_file['person_home_ownership'].map({'RENT': 0, 'MORTGAGE': 1, 'OWN': 2, 'OTHER': 3})
csv_file['loan_intent'] = csv_file['loan_intent'].map({'EDUCATION': 0, 'MEDICAL': 1, 'VENTURE': 2, 'PERSONAL': 3, 'DEBTCONSOLIDATION': 4, 'HOMEIMPROVEMENT': 5,})
csv_file['previous_loan_defaults_on_file'] = csv_file['previous_loan_defaults_on_file'].map({'Yes': 0, 'No': 1})

csv_file

#@title Correlation (only works with numerical data)

import seaborn as sns
import matplotlib.pyplot as plt
correlation = csv_file.corr() # no non-numerical value to remove
correlation

#@title Heatmap
sns.heatmap(correlation, cmap = 'YlGnBu')

#@title Checking imbalance output feature
csv_file['loan_status'].value_counts().sort_index()

#@title Output barchart

import matplotlib.pyplot as plt
bar_chart = csv_file['loan_status'].value_counts()

# Plot
plt.figure(figsize = (6, 4))
bar_chart.plot(kind = 'bar', color = ['red', 'green'])
plt.title('Class Distribution: loan_status')
plt.xlabel('Class (0 = Rejected, 1 = Approved)')
plt.ylabel('<--- Number of Instances --->')
plt.xticks([0, 1], ['Rejected (0)', 'Approved (1)'], rotation = 0)
plt.grid(axis = 'y', linestyle = '--', alpha = 1)
plt.tight_layout()
plt.show()

#@title Normalization via standardization (features have a mean of 0 and a standard deviation of 1)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

rest_data = csv_file.drop(['loan_status'], axis = 1)
target = csv_file['loan_status']
x_train, x_test, y_train, y_test = train_test_split(rest_data, target, test_size = 0.2, random_state = 67) # 80% training, 20% testing
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

#@title Supervised models

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import roc_curve, auc

models = {
    'Logistic Regression': LogisticRegression(),
    'KNN': KNeighborsClassifier(),
    'Neural Network': MLPClassifier(hidden_layer_sizes = (8, 8, 8), activation = 'relu', solver = 'adam', max_iter = 1000, random_state = 67)
}

plt.figure(figsize = (10, 10))
dictn = {}

for name, model in models.items():
  model.fit(x_train_scaled, y_train)
  y_pred = model.predict(x_test_scaled)
  y_prob = model.predict_proba(x_test_scaled)[:, 1]

  fpr, tpr, x = roc_curve(y_test, y_prob)
  roc_auc = auc(fpr, tpr)
  dictn[name] = roc_auc

  plt.plot(fpr, tpr, label = f'{name} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--', label = 'Random Guess')
plt.xlabel('<--- False Positive Rate --->')
plt.ylabel('<--- True Positive Rate --->')
plt.title('ROC Curve Comparison - Loan Approval Dataset')
plt.legend(loc = 'lower right')
plt.grid()
plt.show()

#@title Barchart of Roc Auc score

import matplotlib.pyplot as plt
import pandas as pd

roc_auc_scores = pd.Series(dictn, name = 'ROC AUC')

plt.figure(figsize = (6, 4))
roc_auc_scores.plot(kind = 'bar', color = ['red', 'green', 'blue'])
plt.title('Model Accuracy')
plt.xlabel('Model Name')
plt.ylabel('<--- ROC AUC Score --->')
plt.xticks(rotation = 0)
plt.grid(axis = 'y', linestyle = '--', alpha = 1)
plt.tight_layout()
plt.show()

#@title Neural network confusion matrix, precission, recall, f1 score

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, accuracy_score
from sklearn.metrics import classification_report

mlp = models['Neural Network'] # reuse the model already fitted above
y_pred = mlp.predict(x_test_scaled)
matrix = confusion_matrix(y_test, y_pred)
display = ConfusionMatrixDisplay(confusion_matrix = matrix)
display.plot(cmap = 'Blues')
plt.title('Neural Network Confusion Matrix')
plt.show()

print('\nNeural Network:', accuracy_score(y_test, y_pred))
print('-------------------------------------------------------------------')
print(classification_report(y_test, y_pred, target_names = ['Rejected (0)', 'Approved (1)']))

#@title Logstic regression confusion matrix, precission, recall, f1 score

logistic = models['Logistic Regression'] # reuse the model already fitted above
y_pred = logistic.predict(x_test_scaled)
matrix = confusion_matrix(y_test, y_pred)
display = ConfusionMatrixDisplay(confusion_matrix = matrix)
display.plot(cmap = 'Blues')
plt.title('Logistic Regression Confusion Matrix')
plt.show()

print('\nLogisticRegression:', accuracy_score(y_test, y_pred))
print('-------------------------------------------------------------------')
print(classification_report(y_test, y_pred, target_names = ['Rejected (0)', 'Approved (1)']))

#@title KNN confusion matrix, precission, recall, f1 score

knn = models['KNN'] # reuse the model already fitted above
y_pred = knn.predict(x_test_scaled)
matrix = confusion_matrix(y_test, y_pred)
display = ConfusionMatrixDisplay(confusion_matrix = matrix)
display.plot(cmap = 'Blues')
plt.title('KNN Confusion Matrix')
plt.show()

print('\nKNN:', accuracy_score(y_test, y_pred))
print('-------------------------------------------------------------------')
print(classification_report(y_test, y_pred, target_names = ['Rejected (0)', 'Approved (1)']))